name: FlyCI/CD

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

jobs:
  deploy:
    name: Fly Deploy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd App/client && npm install
      - run: cd App/client && npm run build
      - run: cd App && flyctl deploy --remote-only
